### ISSUE TITLE
Change repo topic

### ISSUE THREAD

**Issue by mdbenito** [daviddao/awesome-data-valuation#8]
I propose to change the topics `data` and `valuation` in the repo settings to [`data-valuation`](https://github.com/topics/data-valuation). The first two are perhaps too generic, whereas the latter is used by several data valuation libraries and code repositories.

I believe that homogenizing usage of topics in the field can increase visibility within github

**Comment by daviddao** [comment]
I agree with you! Thanks for the suggestion and done!
